GET http://www.saultcollege.ca

###

POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent?key=AIzaSyDgH5SQL7cHqsCytw1T5HqGCpb8p1k471A
Content-Type: application/json

{
    "contents": [{
        "parts": [{
            "text": "In one sentence describe the JavaScript Fetch API"
        }]
    }]
}